<?php

namespace FootballManagerBundle\Repository;

use FootballManagerBundle\Entity\Competition;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayersByCompetition(Competition $competition)
    {
        $players = [];

        foreach ($competition->getRegisteredTeams() as $registeredTeam) {
            foreach ($registeredTeam->getRegisteredPlayersAsPlayerInstances() as $player) {
                $players[] = $player;
            }
        }

        return $players;
    }

    public function getTeamsWithRegisteredPlayersInACompetition(Competition $competition)
    {
        $teams = new \ArrayObject();

        foreach ($competition->getRegisteredTeams() as $registeredTeam) {
            if ($registeredTeam->getRegisteredPlayers()->count() > 0) {
                $teams->append($registeredTeam->getTeam());
            }
        }

        return $teams;
    }
}
