<?php

namespace FootballManagerBundle\Repository;

/**
 * PlayerRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
}
