<?php

namespace FootballManagerBundle\Repository;

/**
 * TeamRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
}
